name: CD

on:
  push:
    branches:
      - master

jobs:
  pypi:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'This is ')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: make install
      - run: make release
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
